package com.oms.matching.config;

import com.oms.web.OmsOpenApi;
import io.swagger.v3.oas.models.OpenAPI;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * This service OpenAPI document. Aggregated into the gateway Swagger UI, which lists every service
 * in one dropdown while each document is generated by the service that owns those endpoints - so a
 * controller change updates its own documentation and nobody maintains a spec that drifts.
 */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI openApi() {
        return OmsOpenApi.bearerSecured("matching-engine API", "Read-only depth of book. Operator access only.");
    }
}
