-- =====================================================================================
--  order-service baseline schema.
--
--  Owned exclusively by order-service. No other service reads or writes these tables;
--  they learn about orders from oms.orders.lifecycle.v1.
-- =====================================================================================

CREATE SCHEMA IF NOT EXISTS oms_order;
SET search_path TO oms_order;

-- -------------------------------------------------------------------------------------
--  account — the risk limits a pre-trade check is evaluated against.
--
--  Kept here rather than fetched from another service on the order path: a pre-trade
--  risk check must not have a synchronous dependency on someone else's uptime. Limits
--  change rarely and are administered through this service.
-- -------------------------------------------------------------------------------------
CREATE TABLE account
(
    account_id         VARCHAR(32) PRIMARY KEY,
    display_name       VARCHAR(128)   NOT NULL,
    max_order_notional NUMERIC(18, 4) NOT NULL CHECK (max_order_notional > 0),
    max_position_qty   BIGINT         NOT NULL CHECK (max_position_qty > 0),
    active             BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------------------------------
--  orders — the current state of every order.
--
--  This table is a DERIVED CACHE of the last row in order_audit. The audit trail is the
--  source of truth and can rebuild this table; the reverse is not true. That framing is
--  what makes order_audit an audit trail rather than a change log.
-- -------------------------------------------------------------------------------------
CREATE TABLE orders
(
    order_id        UUID PRIMARY KEY,
    client_order_id VARCHAR(64)    NOT NULL,
    account_id      VARCHAR(32)    NOT NULL REFERENCES account (account_id),
    symbol          VARCHAR(16)    NOT NULL,
    side            VARCHAR(4)     NOT NULL CHECK (side IN ('BUY', 'SELL')),
    order_type      VARCHAR(8)     NOT NULL CHECK (order_type IN ('LIMIT', 'MARKET')),
    time_in_force   VARCHAR(4)     NOT NULL CHECK (time_in_force IN ('DAY', 'IOC', 'FOK')),
    limit_price     NUMERIC(18, 4),
    quantity        BIGINT         NOT NULL CHECK (quantity > 0),
    filled_quantity BIGINT         NOT NULL DEFAULT 0 CHECK (filled_quantity >= 0),
    avg_price       NUMERIC(18, 4),
    status          VARCHAR(20)    NOT NULL,
    reject_reason   VARCHAR(256),
    revision        INTEGER        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),

    -- A LIMIT order without a price, or a MARKET order with one, is nonsense. The
    -- application rejects both, but the database refuses to store them either way:
    -- an invariant that only lives in application code is an invariant that a future
    -- migration script will violate.
    CONSTRAINT ck_orders_limit_price CHECK (
        (order_type = 'LIMIT' AND limit_price IS NOT NULL)
            OR (order_type = 'MARKET' AND limit_price IS NULL)
        ),
    CONSTRAINT ck_orders_fill_le_qty CHECK (filled_quantity <= quantity),

    -- The caller's idempotency key. A retried POST with the same clientOrderId hits
    -- this constraint instead of creating a second order.
    CONSTRAINT uq_orders_client_order_id UNIQUE (account_id, client_order_id)
);

CREATE INDEX ix_orders_account_created ON orders (account_id, created_at DESC);
CREATE INDEX ix_orders_symbol_status ON orders (symbol, status);

-- Partial index: the "show me working orders" query is the hot one, and live orders are
-- a small fraction of the table after a few days of trading.
CREATE INDEX ix_orders_live ON orders (account_id, symbol)
    WHERE status IN ('ROUTED', 'PARTIALLY_FILLED');

-- -------------------------------------------------------------------------------------
--  order_audit — append-only history of every state transition.
-- -------------------------------------------------------------------------------------
CREATE TABLE order_audit
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        UUID           NOT NULL REFERENCES orders (order_id),
    seq             INTEGER        NOT NULL,
    previous_status VARCHAR(20),
    new_status      VARCHAR(20)    NOT NULL,
    reason          VARCHAR(256),
    filled_quantity BIGINT         NOT NULL,
    leaves_quantity BIGINT         NOT NULL,
    avg_price       NUMERIC(18, 4),
    actor           VARCHAR(64)    NOT NULL,
    trace_id        VARCHAR(64),
    occurred_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),

    -- seq is per-order and monotonic, so the history is totally ordered even when two
    -- rows share a millisecond. Timestamps are not an ordering key.
    CONSTRAINT uq_order_audit_seq UNIQUE (order_id, seq)
);

CREATE INDEX ix_order_audit_order ON order_audit (order_id, seq);

-- Append-only, enforced by the database rather than by convention. An UPDATE or DELETE
-- against an audit trail is always either a bug or an attack; either way it should fail
-- loudly rather than succeed quietly.
CREATE OR REPLACE FUNCTION reject_audit_mutation() RETURNS TRIGGER AS
$$
BEGIN
    RAISE EXCEPTION 'oms_order.order_audit is append-only (attempted %)', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_order_audit_immutable
    BEFORE UPDATE OR DELETE
    ON order_audit
    FOR EACH ROW
EXECUTE FUNCTION reject_audit_mutation();

-- -------------------------------------------------------------------------------------
--  order_fill — one row per execution against this order.
-- -------------------------------------------------------------------------------------
CREATE TABLE order_fill
(
    trade_id    UUID           NOT NULL,
    order_id    UUID           NOT NULL REFERENCES orders (order_id),
    symbol      VARCHAR(16)    NOT NULL,
    price       NUMERIC(18, 4) NOT NULL,
    quantity    BIGINT         NOT NULL CHECK (quantity > 0),
    liquidity   VARCHAR(8)     NOT NULL CHECK (liquidity IN ('MAKER', 'TAKER')),
    engine_seq  BIGINT         NOT NULL,
    executed_at TIMESTAMPTZ    NOT NULL,
    recorded_at TIMESTAMPTZ    NOT NULL DEFAULT now(),

    -- THE idempotency guarantee for the trade consumer. Kafka delivers at-least-once,
    -- so the same TradeExecutedEvent will be replayed; the second insert conflicts here
    -- and the handler treats the conflict as "already applied".
    PRIMARY KEY (trade_id, order_id)
);

CREATE INDEX ix_order_fill_order ON order_fill (order_id);

-- -------------------------------------------------------------------------------------
--  position_exposure — order-service's OWN read model of account exposure.
--
--  Deliberately not a call to position-service. A pre-trade risk check runs on the order
--  path, and giving it a synchronous dependency on another service means that service
--  being slow makes order entry slow, and that service being down stops trading. This
--  projection is built from the same trade stream position-service consumes, so the two
--  agree eventually; risk uses its own copy and never blocks on anyone.
--
--  working_* is residual quantity on live orders. Risk must count working quantity, not
--  just filled: an account at its position limit in working orders is already committed.
-- -------------------------------------------------------------------------------------
CREATE TABLE position_exposure
(
    account_id       VARCHAR(32) NOT NULL,
    symbol           VARCHAR(16) NOT NULL,
    net_quantity     BIGINT      NOT NULL DEFAULT 0,
    working_buy_qty  BIGINT      NOT NULL DEFAULT 0 CHECK (working_buy_qty >= 0),
    working_sell_qty BIGINT      NOT NULL DEFAULT 0 CHECK (working_sell_qty >= 0),
    revision         INTEGER     NOT NULL DEFAULT 0,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (account_id, symbol)
);

-- -------------------------------------------------------------------------------------
--  outbox — the transactional outbox (ADR 0004).
--
--  Rows are written in the SAME transaction as the order and audit rows. A separate
--  poller publishes them to Kafka and stamps published_at. This is what makes
--  "persist the order" and "tell the engine about it" atomic without a distributed
--  transaction.
-- -------------------------------------------------------------------------------------
CREATE TABLE outbox
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      UUID         NOT NULL UNIQUE,
    aggregate_id  VARCHAR(64)  NOT NULL,
    event_type    VARCHAR(64)  NOT NULL,
    topic         VARCHAR(128) NOT NULL,
    partition_key VARCHAR(64)  NOT NULL,
    payload       JSONB        NOT NULL,
    trace_id      VARCHAR(64),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at  TIMESTAMPTZ,
    attempts      INTEGER      NOT NULL DEFAULT 0,
    last_error    TEXT
);

-- The poller's only query is "unpublished, oldest first". A partial index keeps that
-- query O(backlog) rather than O(table) once the outbox has millions of published rows.
CREATE INDEX ix_outbox_unpublished ON outbox (created_at)
    WHERE published_at IS NULL;

-- -------------------------------------------------------------------------------------
--  processed_event — consumer-side deduplication.
--
--  Written in the same transaction as the effect it guards, which is what turns
--  at-least-once delivery into effectively-once processing.
-- -------------------------------------------------------------------------------------
CREATE TABLE processed_event
(
    consumer     VARCHAR(64) NOT NULL,
    event_id     VARCHAR(64) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (consumer, event_id)
);

CREATE INDEX ix_processed_event_age ON processed_event (processed_at);
