package com.oms.gateway.api;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * The gateway OpenAPI document, and the Swagger UI that aggregates the four services.
 *
 * <p>springdoc generates paths from the controllers; what it cannot infer is the security scheme.
 * Declaring the bearer scheme here is what puts the Authorize button in Swagger UI - without it the
 * documentation is accurate and unusable, because every try-it-out returns 401 and the reader has
 * no way to supply a token.
 *
 * <p>The aggregation itself is configuration: springdoc.swagger-ui.urls in application.yml points
 * the UI at each service /v3/api-docs. A single dropdown, four documents, each generated by the
 * service that owns those endpoints - so a controller change updates its own documentation and
 * nobody maintains a hand-written spec that drifts.
 */
@Configuration
public class OpenApiConfig {

    private static final String BEARER_SCHEME = "bearerAuth";

    @Bean
    public OpenAPI gatewayOpenApi() {
        return new OpenAPI()
                .info(new Info()
                        .title("OMS Platform API")
                        .version("1.0.0")
                        .description("""
                                Order Management and Market Data Platform.

                                All endpoints except POST /auth/token and GET /oauth2/jwks require a
                                bearer token. Obtain one with:

                                    POST /auth/token
                                    {"username": "trader1", "password": "trader1-password"}

                                Roles: TRADER places and cancels orders; RISK reads positions across
                                accounts but cannot trade; ADMIN reaches operational endpoints and
                                book depth.
                                """)
                        .contact(new Contact().name("OMS Platform")))
                .servers(List.of(new Server().url("/").description("Gateway")))
                .components(new Components().addSecuritySchemes(BEARER_SCHEME,
                        new SecurityScheme()
                                .type(SecurityScheme.Type.HTTP)
                                .scheme("bearer")
                                .bearerFormat("JWT")
                                .description("Paste the accessToken from POST /auth/token")))
                .addSecurityItem(new SecurityRequirement().addList(BEARER_SCHEME));
    }
}
